# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rft6y9Zzm6uZDOnCohusfaSRUMMQ0lo-
"""

print("check")

"""this is to check if it has connected

CALCULATOR
"""

num1 = 35
num2 = 10.5
text1 = "This is a text"

print(num1)
print(num2)
print(text1)
print(type(num1))
print(type(num2))
print(type(text1))

n1 = 250
n2 = 35

#this line is not included in the code, it is just a note
#logic for addition

add=n1+n2
print("addition is =",add)
#dont forget the comma after "" because it shows error

sub=n1-n2
print("subtraction is =",sub)

mul=n1*n2
print("multiplication is =",mul)

div=n1/n2
print("divison is =",div)



"""everytime we take an input, it converts it into a string
hence we get an error, so we add int to make it an integer
"""

n1 = int(input("Give me the first number"))
n2 = int(input("Give me the second number"))

#this line is not included in the code, it is just a note
#logic for addition

add=n1+n2
print("addition is =",add)
#dont forget the comma after "" because it shows error

sub=n1-n2
print("subtraction is =",sub)

mul=n1*n2
print("multiplication is =",mul)

div=n1/n2
print("divison is =",div)

"""PASSWORD ACHIEVING
with the help of a string
"""

division = "Div C"
lecturer = "Divesh Sir"
subject = "Python"
password_by_teacher = 12345
password_by_student = 1234

print("The attedance slot created for")
print("The division is", division)
print("The lecturer is", lecturer)
print("The subject is", subject)

# == means exactly equal to
if password_by_teacher == password_by_student:
  print("attendance given")
else:
  print("attendance not given")
  #if and else should be peeche while print should be aage

division = input("Which Division")
lecturer = input("Which Lecturer")
subject = input("Which subject")
password_by_teacher = 12345
password_by_student = int(input("Give password"))

print("The attedance slot created for")
print("The division is", division)
print("The lecturer is", lecturer)
print("The subject is", subject)

# == means exactly equal to
if password_by_teacher == password_by_student:
  print("attendance given")
else:
  print("attendance not given")
  #if and else should be peeche while print should be aage

