# -*- coding: utf-8 -*-
"""dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAZ4PkZb2ANHVmlGw0wSwUHG_CtOea52

DICTIONARY
KEY- word we are trying to find
VALUE - meaning of that word
"""

list1=[100,101,102]
print(list1)
print(type(list1))

artist = {
    "name" : "Suhana",
    "age" : 18,
    "type" : "student"
}
print(artist)
print(type(artist))

student = {
    "name" : "xyz",
    "age" : 18,
    "course" : "bsc eco"
}
print(student)
print(type(student))

print(student.keys())
print(student.values())

"""Accessing items of a dictionary"""

print(student["course"])
print(student["age"])
print(student["name"])

"""Modifying a value"""

student["age"]=19
print(student)

"""Adding a new item"""

student["hobby"] = "photography"
print(student)

"""  Removing an item"""

student.pop("course")
print(student)

"""GROCERY STORE"""

print("WELCOME TO OUR GROCERY STORE")
print("-"*45)
#shopkeeper's side
store = {
    "Oil" : 60,
    "Milk" : 35,
    "Eggs" : "48"
}
print("These things are available")
print(store)
print("-"*45)
#customer's side
print("Shopkeeper asks : What do you want to buy?")
item_to_buy = input("What do you want?  - ")
#everytime, the customer wont ask for oil, so to make it dynamic we make it an input
quantity = int(input("How many do you want?  - "))
print("Customer says : I want",quantity, "qtys", "of", item_to_buy)
print("-"*45)
#generating a bill
price = store[item_to_buy]
total = price*quantity
print("Your total bill is",total)

