# -*- coding: utf-8 -*-
"""doneontime.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8fpI-2lq_J3O6QAhwLbO5FcprRBXj7I
"""

# Deadline Risk Predictor

def predict_deadline_risk(total_tasks, tasks_completed, total_days, days_passed, avg_hours_day):

    if tasks_completed > total_tasks:
        return "Error: Tasks completed cannot exceed total tasks."

    if days_passed > total_days:
        return "Error: Days passed cannot exceed total days."

    # Current velocity (tasks per day)
    velocity = tasks_completed / days_passed if days_passed > 0 else 0

    remaining_tasks = total_tasks - tasks_completed
    days_remaining = total_days - days_passed

    # Required daily rate
    required_rate = remaining_tasks / days_remaining if days_remaining > 0 else float('inf')

    # Productivity (tasks per hour)
    productivity = velocity / avg_hours_day if avg_hours_day > 0 else 0

    # Performance ratio
    performance_ratio = velocity / required_rate if required_rate > 0 else 1

    # Risk score calculation
    risk_score = (1 - performance_ratio) * 100
    risk_score += (1 - productivity) * 20

    # Clamp between 0–100
    miss_prob = max(0, min(100, risk_score))

    # Risk classification
    if miss_prob < 25:
        risk_level = "Low"
    elif miss_prob < 60:
        risk_level = "Medium"
    else:
        risk_level = "High"

    # Projection
    projected_additional = velocity * days_remaining
    projected_total = tasks_completed + projected_additional

    return {
        "Current Work Velocity (tasks/day)": round(velocity, 2),
        "Required Daily Rate (tasks/day)": round(required_rate, 2),
        "Probability of Missing Deadline (%)": round(miss_prob, 2),
        "Risk Level": risk_level,
        "Remaining Tasks": remaining_tasks,
        "Days Remaining": days_remaining,
        "Projected Completion": round(projected_total, 2)
    }


# -------- MAIN PROGRAM -------- #

print("🚀 Deadline Risk Predictor\n")

total_tasks = float(input("Enter total number of tasks: "))
tasks_completed = float(input("Enter tasks completed: "))
total_days = float(input("Enter total days given: "))
days_passed = float(input("Enter days passed: "))
avg_hours_day = float(input("Enter average hours worked per day: "))

result = predict_deadline_risk(
    total_tasks,
    tasks_completed,
    total_days,
    days_passed,
    avg_hours_day
)

print("\n----- Prediction Result -----\n")

if isinstance(result, dict):
    for key, value in result.items():
        print(f"{key}: {value}")
else:
    print(result)

