# -*- coding: utf-8 -*-
"""lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpCYbSAyUiWZ1Ykapvf4r3rNpDOIjscx
"""

print("check")

"""Making A list"""

#list of roll numbers - this is just for reference
my_list = [101,102,103,104]

print(my_list)

"""LIST OPERATIONS

What all things we can do with lists

P   Y   T   H   O   N
           0   1   2   3   4   5
          -6  -5  -4  -3  -2  -1
      This is how python counts the position

APPEND - means add something to the end
"""

my_list.append(105)
print(my_list)

"""INSERT - means to add something to a particular position, first give position then what to insert"""

my_list.insert(-6,100)
print(my_list)

"""if you shift + enter twice- you will see that it will add the number twice

POP - removes the last item
"""

my_list.pop()
print(my_list)

"""REMOVE - specifically removing a particular thing"""

my_list.remove(104)
print(my_list)

"""CREATE A SHOPPING MART"""

print("WELCOME TO SEE MART")
print("-"*19)

shopping_cart = ["donuts","bananas","cakes","cupcakes","ice cream"]
print(shopping_cart)
print("-"*55)

add_item = "tshirts"
shopping_cart.append(add_item)
print(shopping_cart)
print("-"*63)

remove_item = "tshirts"
shopping_cart.remove(remove_item)
print(shopping_cart)
print("-"*55)

# make same functionality for spotify likes songs

print("LIKED SONGS IN SPOTIFY")
print("."*22)

genre_lists = ["ROCK","POP","HINDI","SUFI","GHAZAL"]
print(genre_lists)
print("."*43)

add_item = "romantic"
genre_lists.append(add_item)
print(genre_lists)
print("-"*54)

remove_item = "SUFI"
genre_lists.remove(remove_item)
print(genre_lists)
print("-"*46)



