# -*- coding: utf-8 -*-
"""python day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106dCuQ33jqRUNYXpAHU8Q_Hac2BGbhMo
"""



"""SHIFT + ENTER ------ NEXT LINE
CTRL + ENTER ------- SAME LINE
"""



"""1. WHOLE NUMBERS"""

population = 12736515
print(population)

unemployment_rate = 36
print(unemployment_rate)

years_until_2030 = 2030 - 2025
print(years_until_2030)

type(years_until_2030)

"""2. FLOAT
DECIMAL POINTS
"""

inflation_rate = 5.42
gdp_growth = 6.3
print("The Inflation Rate is =", inflation_rate)

"""A text is added in " "
"""



"""3. STRING  - text"""

name = "Suhana"
print(name)
print("Her name is", name)

type(name)

"""4.LIST - list of values separated by a comma"""

food=["pizza",156.3]
print(food)

type(food)



"""HOW LIST SOLVES YOUR PROBLEMS"""

numbers = [346, 234,653,123,435,76,875,100,18]
print(numbers)
numbers.append(23)
print(numbers)
numbers.pop(2)
print(numbers)

print(sorted(numbers))

"""if you miss a number, and want to add it later, we used numbers.append

and then if you want to remove a number, you use numbers.pop and then in brakets give the position of the number, and in python 1st number is actually 0th

TUPLE - IMMUTABLE
"""

NUMBER = (1,6,"HI, 3.7")
print(NUMBER)

"""Difference between tuple and a list is that you can add elements in list later, but in tuple you cannot"""

type(NUMBER)

