# -*- coding: utf-8 -*-
"""sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6ZnMcXCC1Hn_4rp3YD8ue2ZUc-cSSFn
"""

names = ["Suhana","Vidhi", "Sukriti","Srishti","Yashodhara","Sanya","Sanya"]
print(names)

"""SETS

ONLY when we want unique elements
eg: ROLL no. - 100,102
colour : red, green
city : Bangalore, Pune
Genre : Hip Hop, Classical
"""

roll_numbers = {101,102,105,100, 100}
print(roll_numbers)
print(type(roll_numbers))

cities = {"Pune","Delhi", "Bangalore","Hyderabad"}
print(cities)

cities.remove("Hyderabad")
print(cities)

cities.add("Pune")
print(cities)

"""MUSIC GENRE ANALYSER

"""

friend1 = {"Classical","Pop", "Hiphop","edm"}
friend2 = {"Classical","country", "bollywood","sufi"}
print(friend1)
print(friend2)

"""

UNION of 2 set

```
# This is formatted as code
```

s
add a pipe |"""

print(friend1 | friend2)

"""INTERSECTION of 2 SETS add a &"""

print(friend1&friend2)

