# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M091kk0335mgM-2WaKw7HxR49yZHvjYx

LISTS REVISING
"""

l1 = [3,2,4,5,"etc",{"key1" : "value1"}, ["why","ok"]]
print(l1)
print(type(l1))

l2 = [1,5,5,6]
print(l2)

print(l2[3])

"""REPLACING AN ELEMENT"""

l2[3] = 40
print(l2)

"""dictionary"""

student = {
    "name" : "Yasho",
    "age"  : 18
}
print(student)
print(type(student))

student["age"]

student["age"] = 19
print(student)

"""TUPLE (elder brother of list)

Also instead of [] used for LIST, () is used for TUPLE

everything needs to be in ORDER, also we cannot ADD or DELETE anything
"""

calender = (1,2,3,4,5,6,7,8)
print(calender)
print(type(calender))

calender[2]

"""MAKING MOVIE CINEMA"""

print("SSE MOVIE THEATRE")
movies = ["Spiderman", "Avengers", "Incredible"]
print("Available Shows")
print(movies)

new_movie = "Dhurandar"
movies.append(new_movie)
print(movies)

movies.pop()
print(movies)

seats = ("A1","A2","A3","A4","A5","A6","A7")
print("Available seats are", seats)

bookings = {}

movie_to_watch = "Avengers"
seat = "A1"
booking_key = (movie_to_watch + "-" + seat)
print(booking_key)

bookings[booking_key] = "BOOKED"
print("Booking Successful")
print(bookings)

movie_to_watch = input("Which Movie?")
seat = input("Which seat?")
booking_key = (movie_to_watch + "-" + seat)
print(booking_key)

bookings[booking_key] = "BOOKED"
print("Booking Successful")
print(bookings)

